---
# https://eslint.org/docs/user-guide/configuring#specifying-environments
plugins:
  # https://github.com/jest-community/eslint-plugin-jest
  - jest

env:
  node: true
  jest: true

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'

rules:
  no-console: 0
  import/extensions: 0